version: '3.8'

services:
  freelancer-api:
    build: .
    ports:
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=sqlserver,1433
      - DB_NAME=FreelancerApiDb
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
    depends_on:
      - sqlserver
    networks:
      - freelancer-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - freelancer-network

volumes:
  sqlserver_data:

networks:
  freelancer-network:
    driver: bridge